if(NOT PROJECT_IS_TOP_LEVEL OR soa_PACKAGING_MAINTAINER_MODE)
    option(soa_ENABLE_IPO "Enable IPO/LTO" OFF)
  else()
    option(soa_ENABLE_IPO "Enable IPO/LTO" ON)
  endif()

macro(soa_enable_ipo)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT result OUTPUT output)
  if(result)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  else()
    message(SEND_ERROR "IPO is not supported: ${output}")
  endif()
endmacro()
soa_enable_ipo()