if(NOT PROJECT_IS_TOP_LEVEL OR soa_PACKAGING_MAINTAINER_MODE)
  option(soa_ENABLE_SANITIZER_UNDEFINED "Enable address undefined" OFF)
else()
  option(soa_ENABLE_SANITIZER_UNDEFINED "Enable address undefined" ${SUPPORTS_ASAN})
endif()