if(NOT PROJECT_IS_TOP_LEVEL OR soa_PACKAGING_MAINTAINER_MODE)
  option(soa_ENABLE_SANITIZER_ADDRESS "Enable undefined sanitizer" OFF)
else()
  option(soa_ENABLE_SANITIZER_ADDRESS "Enable undefined sanitizer" ${SUPPORTS_UBSAN})
endif()