if(soa_ENABLE_HARDENING AND NOT soa_ENABLE_GLOBAL_HARDENING)
  if(NOT SUPPORTS_UBSAN 
    OR soa_ENABLE_SANITIZER_UNDEFINED
    OR soa_ENABLE_SANITIZER_ADDRESS
    OR soa_ENABLE_SANITIZER_THREAD
    OR soa_ENABLE_SANITIZER_LEAK)
    set(ENABLE_UBSAN_MINIMAL_RUNTIME FALSE)
  else()
    set(ENABLE_UBSAN_MINIMAL_RUNTIME TRUE)
  endif()
endif()